### ISSUE TITLE
Typescript config file

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape-hardhat#109]
### Overview

Add support for `hardhat.config.ts`.  Pretty common for projects to use the typescript file, and the JS one created by Ape can cause conflicts.

### Specification

At a glance I didn't see how the JS file was consumed so I'm not sure all what needs to be done for this.

**Comment by fubuloubu** [comment]
Related: as a brownie user, there's a file that will have been generated by brownie already, so have ape check if certain fields are mis-configured vs. what it expects and inform the user that ape may not function as expected.

The biggest issue I've seen is with mnemonics.

**Comment by unparalleled-js** [comment]
`hardhat node` does let you use `--config` to point to another config file..

We could generate one in the `.ape` directory and always reference that one. That way, the brownie one or the active hardhat one wouldn't matter.

**Comment by unparalleled-js** [comment]
The open only shows an error right now but debating on the `.ape` idea.

**Comment by fubuloubu** [comment]
Can have it default to `~/.ape/hardhat/config.js`, and you can override it via config to point to a local file, essentially making it opt in

**Comment by mikeshultz** [comment]
For existing project integration, I think it might be a mistake to default to running against your own hardhat config instead of a pre-existing one.  Especially since `ape_hardhat` will run pre-existing hardhat deployments when starting up a local node.

For instance, [looking at this config file](https://github.com/OriginProtocol/nft-launchpad/blob/master/contracts/hardhat.config.ts), it diverges at some basic config levels compared to `ape_hardhat`.  For instance, the `hardfork` setting which is important for some of the contracts in this project.

I realize `ape_hardhat`'s scope is limited, but if co-existence is a goal (rather than just running a generic node), it would be great to use the config file that's there.  Opt-in would work, I guess, but seems like a simpler and friendlier approach might just be to not write the default js config file if the ts file exists.

**Comment by fubuloubu** [comment]
> For existing project integration, I think it might be a mistake to default to running against your own hardhat config instead of a pre-existing one. Especially since `ape_hardhat` will run pre-existing hardhat deployments when starting up a local node.
> 
> For instance, [looking at this config file](https://github.com/OriginProtocol/nft-launchpad/blob/master/contracts/hardhat.config.ts), it diverges at some basic config levels compared to `ape_hardhat`. For instance, the `hardfork` setting which is important for some of the contracts in this project.
> 
> I realize `ape_hardhat`'s scope is limited, but if co-existence is a goal (rather than just running a generic node), it would be great to use the config file that's there. Opt-in would work, I guess, but seems like a simpler and friendlier approach might just be to not write the default js config file if the ts file exists.

I think this is a good middle-of-the-road approach that stops some fustrations with how it works currently

How it works currently is that ape fails to function at all if you don't set up the config file in a specific way. That's been leading to a lot of developer frustration into thinking that the plugin is broken. By using the user's installation default in `~/.ape/hardhat/config.js` (initialized via ape but updateable if anyone wants to) and making a warning that we detected a non-standard `config.js` locally, and further allowing the developer to opt-in to using the local file, we can avoid this frustration by making it much clearer that the recommended course of action is to ensure that the local file is compatible with Ape, and setting it in `ape-config.yaml` to use the local file if it does indeed matter for the project.
