### ISSUE TITLE
set balance for impersonated accounts in mainnet-fork

### ISSUE THREAD

**Issue by bout3fiddy** [ApeWorX/ape-hardhat#116]
### Overview

Provide methods for setting eth/native token balance of any address.

### Specification

```
acc = ape.account[0x...]
acc.balance += 10**18
```

**Comment by unparalleled-js** [comment]
https://github.com/ApeWorX/ape-hardhat/blob/main/ape_hardhat/provider.py#L443

**Comment by fubuloubu** [comment]
Sorry about the confusion
