### ISSUE TITLE
Add ability to spin up a hardhat node via `ape hardhat node` [APE-725]

### ISSUE THREAD

**Issue by sentilesdal** [ApeWorX/ape-hardhat#128]
### Overview

Using the hardhat plugin, add the ability to spin up a local hardhat node.  The idea here is to be able to run
```
ape hardhat node
```
from the terminal so that apeworx projects can connect to a local hardhat node

### Dependencies

https://github.com/NomicFoundation/hardhat

**Comment by fubuloubu** [comment]
So, can implement that pretty easily with a a cli extension

Broad strokes:
1. Add `ape_hardhat/_cli.py` file
2. Put this in the file to get started:
```py
import click


@click.group(short_help="Run hardhat commands")
def cli():
    """
    Write a long description here... 
    """
```
3. Add this line to the `setup` function under `setup.py`:
```py
entry_points={"ape_cli_subcommands": ["ape_hardhat=ape_hardhat._cli:cli"]},
```
4. Then you would create a new click command in the CLI project using `@cli.command` for the particular command you want to run.

If you do that to get started on a PR (under this repo) we can review it and get it across the finish line!

**Comment by unparalleled-js** [comment]
We could also do this:

```
ape node --provider ::hardhat
ape node --provider starknet:local:devnet
ape node --provider ::geth
```

**Comment by sentilesdal** [comment]
> We could also do this:
> 
> ```
> ape node --provider ::hardhat
> ape node --provider starknet:local:devnet
> ape node --provider ::geth
> ```

Yeah this looks great actually

**Comment by fubuloubu** [comment]
Side note: we can also add support for calling `hardhat` or `foundry` commands (e.g. `ape foundry test ...`, `ape foundry cast ...`, etc.) via these CLIs

**Comment by unparalleled-js** [comment]
@fubuloubu the `SubprocessProvider` already has an API method for starting the process

**Comment by unparalleled-js** [comment]
basically, if it a subprocess provider, call `start()`. Else, `TypeError` or `NetworkError`. The specifics don't really matter, like what network it is. you can still use forked networks. All you need is a `SubprocessProvider`, which makes sense.
