### ISSUE TITLE
Wrong error when hardhat is not installed correctly [APE-910]

### ISSUE THREAD

**Issue by poolpitako** [ApeWorX/ape-hardhat#141]
### Environment information

- `ape` and plugin versions:
Installed Plugins:
  infura      0.6.1
  vyper       0.6.4
  hardhat     0.6.4

```
$ ape --version
0.6.8

$ ape plugins list
Installed Plugins:
  hardhat     0.6.4
  vyper       0.6.4
  infura      0.6.1

# ...copy and paste result of above command here...
```

- Python Version: 3.10.6
- OS: macOS

### What went wrong?
Hardhat was installed with 
```npm install -g hardhat```

but apparently npx wants hardhat to be installed locally.
When running ape I was getting the following error:
```

INTERNALERROR> ape.exceptions.RPCTimeoutError: Timed out waiting for successful RPC connection to the 'Hardhat node' process (20 seconds).
```

### How can it be fixed?
The ape plugin should check that hardhat is installed correctly.
A simple print of `npx hardhat --version` would help debug issues as well.

**Comment by antazoey** [comment]
hmm, we are already doing that.
i guess it didn't trigger though.

**Comment by antazoey** [comment]
ok, seems like this happens when hh is installed both globally _and_ locally
