### ISSUE TITLE
Use logger.debug for network-related print statements.

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-hardhat#3]
### Overview

Use `logger.debug()` for `print()` statements (or whichever log lever makes sense)

### Specification

Currently, it is a bit noisy when using this plugin. I know @lost-theory as this work somewhere, am wondering if you could open a PR? Just would like to log the Network retries at the debug level. It will help out demos dependent on hardhat.

**Comment by lost-theory** [comment]
Never mind on those 3 issues, it seems like they will all be fixed when eth-ape `0.1.0a25` is released.
