### ISSUE TITLE
Add test for impersonated account and bump minimum ape requirement

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-hardhat#38]
### Overview

Once ape is released, bump the required version so we can add a test to make sure we can se impersonated accounts

**Comment by unparalleled-js** [comment]
- [ ] Also make sure `ContractInstances` automatically get impersonated

(see https://github.com/ApeWorX/ape/pull/619)

**Comment by sabotagebeats** [comment]
https://github.com/ApeWorX/ape-hardhat/pull/44

**Comment by sabotagebeats** [comment]
It seems this should be bumped at the next release that includes https://github.com/ApeWorX/ape/pull/619

**Comment by sabotagebeats** [comment]
can we reuse most of this test from ape core? 

https://github.com/sabotagebeats/ape/blob/b2b19286c583c7239553c2d307280717a0ba6594/tests/functional/test_accounts.py#L172-L180

**Comment by unparalleled-js** [comment]
@sabotagebeats  Yes, but instead of expecting a failure we expect it to work
