### ISSUE TITLE
ape plugins add alchemy from readme doesn't work

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape-hardhat#41]
### Environment information

* `ape` and plugin versions:

$ ape --version
`0.1.4.dev4+gcc458e80`

$ ape plugins list
```
Installed Plugins:
  tokens       
  hardhat      
  infura       
  vyper        
  ens          
  alchemy      
  solidity     
  etherscan
```

* Python Version: 3.9.9
* OS: wsl2 linux

### What went wrong?

Please include information like:

* what command you ran
`ape plugins add alchemy`
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
following docs
* full output of the error you received
`Error: No such command 'add'.`

### How can it be fixed?

update docs

**Comment by NotPeopling2day** [comment]
Fixed in https://github.com/ApeWorX/ape-hardhat/pull/40
